In [1]:
import numpy as np
import pandas as pd

In [29]:
df = pd.read_csv('sentiment_tweets3.csv')
df.head()

,Index,message to examine,label (depression result)
0,106,just had a real good moment. i missssssssss hi...,0
1,217,is reading manga http://plurk.com/p/mzp1e,0
2,220,@comeagainjen http://twitpic.com/2y2lx - http:...,0
3,288,@lapcat Need to send 'em to my accountant tomo...,0
4,540,ADD ME ON MYSPACE!!! myspace.com/LookThunder,0


In [31]:
df.shape

(10314, 3)

In [30]:
df['label (depression result)'].value_counts()

label (depression result)
0    8000
1    2314
Name: count, dtype: int64

In [32]:
df.drop(['Index'],axis=1,inplace=True)

In [33]:
df.isna().sum()

message to examine           0
label (depression result)    0
dtype: int64

In [34]:
df.duplicated().sum()

np.int64(31)

In [35]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re

In [36]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [37]:
stop_words = set(stopwords.words('english'))

from nltk.stem import WordNetLemmatizer

lem = WordNetLemmatizer()

def pre(text):
    
    stemmed = re.sub(r'[^a-zA-Z ]','',text)
    stemmed = stemmed.lower()
    stemmed = stemmed.split()
    stemmed = [lem.lemmatize(i,pos='v') for i in stemmed if i not in stopwords.words('english')]
    stemmed = ' '.join(stemmed)
    return stemmed

In [38]:
df['message to examine'] = df['message to examine'].apply(pre)
df['message to examine']

0                       real good moment missssssssss much
1                             read manga httpplurkcompmzpe
2        comeagainjen httptwitpiccomylx httpwwwyoutubec...
3        lapcat need send em accountant tomorrow oddly ...
4                        add myspace myspacecomlookthunder
                               ...                        
10309    depression g herbo mood im do stress people do...
10310    depression succumb brain make feel like youll ...
10311    ketamine nasal spray show promise depression s...
10312          dont mistake bad day depression everyone em
10313                                                     
Name: message to examine, Length: 10314, dtype: str

In [39]:
x = df['message to examine']
y = df['label (depression result)']

In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [41]:
vectorizer = TfidfVectorizer()
vectorizer.fit(x)
x = vectorizer.transform(x)

In [42]:
print(x)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 87654 stored elements and shape (10314, 20931)>
  Coords	Values
  (0, 6672)	0.2597987192247522
  (0, 12212)	0.6600449529406147
  (0, 12328)	0.48544731367637217
  (0, 12596)	0.32823824803554924
  (0, 15516)	0.39172164065538595
  (1, 8050)	0.6541743233556511
  (1, 11495)	0.6541743233556511
  (1, 15508)	0.3796207440648523
  (2, 3255)	0.548378613017889
  (2, 8696)	0.5913040236564336
  (2, 8790)	0.5913040236564336
  (3, 97)	0.3485441152408976
  (3, 5118)	0.2683374673700505
  (3, 5410)	0.18835684881929396
  (3, 5439)	0.2831384110175009
  (3, 10585)	0.3485441152408976
  (3, 12889)	0.17712587668882945
  (3, 13388)	0.3485441152408976
  (3, 15630)	0.2936398476580236
  (3, 16631)	0.22319115617421556
  (3, 18008)	0.22626049421255348
  (3, 18255)	0.302813733687656
  (3, 18654)	0.20466211639434817
  (3, 18885)	0.1914301648033193
  (3, 19912)	0.24303508708207736
  :	:
  (10310, 2077)	0.3898408369072287
  (10310, 4234)	0.14715749459123953
 

In [43]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3,stratify=y,random_state=2)

In [44]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(xtrain,ytrain)
ypred = model.predict(xtest)
ypred

array([0, 0, 1, ..., 1, 0, 1], shape=(3095,))

In [75]:
print(xtest)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 26662 stored elements and shape (3095, 20931)>
  Coords	Values
  (0, 165)	0.44086903805961686
  (0, 4701)	0.2717098851844013
  (0, 4778)	0.6028001559011119
  (0, 6800)	0.2868895837943412
  (0, 16571)	0.2722116013604667
  (0, 18453)	0.31081504693083595
  (0, 19224)	0.3397490530016604
  (1, 3472)	0.5017664676801399
  (1, 9900)	0.5240189595494292
  (1, 12436)	0.2732360522013624
  (1, 16571)	0.2366357054253918
  (1, 19032)	0.5240189595494292
  (1, 19879)	0.26150387123808305
  (2, 4234)	0.18221029935580993
  (2, 6691)	0.45739208512206647
  (2, 10290)	0.6833254722227532
  (2, 13137)	0.5391272449875874
  (3, 4316)	0.47290226449952105
  (3, 8628)	0.5343887903988698
  (3, 10874)	0.2195259510865295
  (3, 11431)	0.49559511176522864
  (3, 12963)	0.253956321218914
  (3, 20768)	0.3639946398426476
  (4, 2031)	0.5530798188870363
  (4, 8606)	0.5984507176188562
  :	:
  (3092, 15804)	0.32588900539610816
  (3092, 17834)	0.3298490616794173
  (30

In [76]:
print(ypred)

[0 0 1 ... 1 0 1]


In [45]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(ytest,ypred)
acc

0.9696284329563812

In [46]:
ytrain_pred = model.predict(xtrain)

In [47]:
train_acc = accuracy_score(ytrain,ytrain_pred)
train_acc

0.9846239091286881

In [88]:
text = "Ketamine Nasal Spray Shows Promise Against Depression, Suicide #health https://cmun.it/4sjligk "

In [100]:
sent = pre(text)

In [101]:
sent

'ketamine nasal spray show promise depression suicide health httpscmunitsjligk'

In [102]:
import numpy as np
data = vectorizer.transform(np.array([sent]))
print(data)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 9 stored elements and shape (1, 20931)>
  Coords	Values
  (0, 4234)	0.11747579449791255
  (0, 7221)	0.26810046077543287
  (0, 8137)	0.44055798730276113
  (0, 10246)	0.38275501782281784
  (0, 12817)	0.40857590742763805
  (0, 14952)	0.32991816895297665
  (0, 16917)	0.2451946702069388
  (0, 17543)	0.38986759000562227
  (0, 17918)	0.29296996846775164


In [103]:
model.predict(data)

array([1])